"""base migration

Revision ID: 7f0351f9271c
Revises: 
Create Date: 2023-03-10 14:22:28.199085

"""
from alembic import op
import sqlalchemy as sa
import citext


# revision identifiers, used by Alembic.
revision = '7f0351f9271c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_authors',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('auth_id'),
    sa.UniqueConstraint('author')
    )
    op.create_table('new_collections',
    sa.Column('coll_identifier', citext.CIText(), nullable=False),
    sa.Column('coll_name', sa.String(), nullable=False),
    sa.Column('coll_location', sa.String(), nullable=False),
    sa.Column('coll_type', sa.String(), nullable=False),
    sa.Column('coll_source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('coll_identifier')
    )
    op.create_table('new_books',
    sa.Column('date_of_publication', sa.Date(), nullable=False),
    sa.Column('number_of_pages', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('place_of_publication', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('coll_identifier', citext.CIText(), nullable=False),
    sa.ForeignKeyConstraint(['coll_identifier'], ['new_collections.coll_identifier'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('volume', 'coll_identifier')
    )
    op.create_table('new_periodicals',
    sa.Column('date_of_journal', sa.Date(), nullable=False),
    sa.Column('number_of_pages', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('coll_identifier', citext.CIText(), nullable=False),
    sa.ForeignKeyConstraint(['coll_identifier'], ['new_collections.coll_identifier'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('date_of_journal', 'coll_identifier')
    )
    op.create_table('book_authors',
    sa.Column('book_id', citext.CIText(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['new_authors.auth_id'], ),
    sa.ForeignKeyConstraint(['book_id', 'volume'], ['new_books.coll_identifier', 'new_books.volume'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_authors')
    op.drop_table('new_periodicals')
    op.drop_table('new_books')
    op.drop_table('new_collections')
    op.drop_table('new_authors')
    # ### end Alembic commands ###
